name:                aocd1
version:             0.1.0.0
github:              "githubuser/aocd1"
license:             BSD3
author:              "Maximilian Gaber"
maintainer:          "maxi.gaber@gmail.com"
copyright:           "2020 Maximilian Gaber"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aocd1#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- mtl
- megaparsec
- split

library:
  source-dirs: src

executables:
  aocd1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aocd1

tests:
  aocd1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aocd1
